//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by DRMBuilder.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDR_MAINFRAME                   128
#define IDR_DRMBuilderTYPE              129
#define IDD_DIALOG_INPUT_VARIABLE       130
#define IDD_DIALOG_OUTPUT_VARIABLE      131
#define IDD_DIALOG_SOLVER_INPUT         132
#define IDD_DIALOG_MODEL_PARAMETER      133
#define IDD_DIALOG_MODEL_PARAMETER_NARMA 134
#define IDI_ICON_CCSI                   134
#define IDD_DIALOG_PLOT_RESULT          135
#define IDD_DIALOG_ACM_PATHNAME         136
#define IDD_DIALOG_NOISE                138
#define IDC_LIST_INPUT                  1001
#define IDC_EDIT_NAME                   1006
#define IDC_EDIT_DESC                   1007
#define IDC_EDIT_DEFAULT                1008
#define IDC_EDIT_LOWER_LIMIT            1009
#define IDC_EDIT_UNIT1                  1009
#define IDC_EDIT_UPPER_LIMIT            1010
#define IDC_CHECK_VARIED                1011
#define IDC_BUTTON_DEFAULT              1012
#define IDC_EDIT_NX                     1013
#define IDC_LIST_OUTPUT                 1014
#define IDC_EDIT_UNIT                   1014
#define IDC_EDIT_DT                     1015
#define IDC_CHECK_RAMP                  1015
#define IDC_EDIT_NPOINT                 1016
#define IDC_EDIT_RAMP_RATE              1016
#define IDC_EDIT_NDURATION              1017
#define IDC_LIST_DURATION               1018
#define IDC_CHECK_IREVERSE              1019
#define IDC_EDIT_NDT                    1020
#define IDC_EDIT_DT_MIN_SOLVER          1021
#define IDC_EDIT_NNEURON_HID            1022
#define IDC_EDIT_NORDER                 1024
#define IDC_EDIT_POLE                   1025
#define IDC_EDIT_NMAX_ITER_BP           1026
#define IDC_EDIT_WEIGHT_INIT            1027
#define IDC_EDIT_NMAX_ITER_RED          1028
#define IDC_RADIO_USER                  1029
#define IDC_RADIO_OPTIMIZED             1030
#define IDC_EDIT_NHISTORY               1031
#define IDC_STATIC_TIME                 1032
#define IDC_STATIC_RAMP_RATE            1033
#define IDC_STATIC_TIME_MIN             1033
#define IDC_EDIT_TIME_SAMPLE            1034
#define IDC_EDIT_TIME_MIN_SOLVER        1035
#define IDC_STATIC_TIME_SAMPLE          1036
#define IDC_STATIC_TIME_MIN_SOLVER      1037
#define IDC_BUTTON_SELECT_ALL_IN        1038
#define IDC_BUTTON_SELECT_ALL_OUT       1039
#define IDC_RADIO_BP_LAG                1039
#define IDC_BUTTON_DESELECT_ALL_IN      1040
#define IDC_RADIO_IPOPT_LAG             1040
#define IDC_BUTTON_DESELECT_ALL_OUT     1041
#define IDC_EDIT_NMAX_ITER_LAG          1041
#define IDC_RADIO_BP_RED                1042
#define IDC_RADIO_IPOPT_RED             1043
#define IDC_BUTTON_USE_DEFAULT          1044
#define IDC_BUTTON_RESET                1045
#define IDC_EDIT_PATHNAME               1048
#define IDC_BUTTON_BROWSE               1049
#define IDC_EDIT_NOUTPUT                1050
#define IDC_EDIT_FQ_STATE               1051
#define IDC_EDIT_FR_OUTPUT              1052
#define IDC_CHECK_ERROR                 1053
#define IDC_CHECK_STEP_CHANGE           1054
#define IDC_CHECK3                      1055
#define IDC_CHECK_CORRELATION           1055
#define ID_SETUP_ACMMODEL               32771
#define ID_SETUP_INPUTPARAMETERS        32772
#define ID_SETUP_OUTPUTVARIABLES        32773
#define ID_SETUP_INPUTSAMPLLING         32774
#define ID_SETUP_INPUTVARIABLES         32775
#define ID_SETUP_PREPAREIDENTIFICATION  32776
#define ID_BUILD_LAUNCHHIGH             32777
#define ID_BUILD_BUILDREDUCEDMODEL      32778
#define ID_Menu                         32779
#define ID_SETUP_PREPAREVALIDATIONSEQUENCE 32780
#define ID_SETUP_PREPARE_TRAINING_SEQUENCE 32781
#define ID_SETUP_PREPARE_VALIDATION_SEQUENCE 32782
#define ID_BUILD_SHOWTRAININGRESULTS    32783
#define ID_BUILD_SHOWVALIDATIONRESULTS  32784
#define ID_BUILD_LAUNCH_SIMULATION      32785
#define ID_BUILD_GENERATE_REDUCED_MODEL 32786
#define ID_BUILD_SHOW_TRAINING_RESULTS  32787
#define ID_BUILD_SHOW_VALIDATION_RESULTS 32788
#define ID_FILE_EXPORTD                 32789
#define ID_SETUP_CHOOSEHIGH             32790
#define ID_CHOOSEHIGH_ACM               32791
#define ID_CHOOSEHIGH_GPROMS            32792
#define ID_SETUP_CHOOSE_ACM             32793
#define ID_SETUP_CHOOSE_GPROMS          32794
#define ID_BUILD_LAUNCH_TRAINING_SIMULATION 32795
#define ID_BUILD_LAUNCHVALIDATIONSIMULATION 32796
#define ID_BUILD_LAUNCH_VALIDATION_SIMULATION 32797
#define ID_CHOOSEHIGH_DML               32798
#define ID_SETUP_CHOOSE_DML             32799
#define ID_CHOOSEHIGH_MATLABSCRIPTFILE  32800
#define ID_SETUP_CHOOSE_MATLAB          32801
#define ID_BUILD_PREDICT_TRAINING_DATA  32802
#define ID_BUILD_PREDICT_TRAINING_RESPONSE 32803
#define ID_BUILD_PREDICT_VALIDATION_RESPONSE 32804
#define ID_POSTPROCESS_PREDICT          32805
#define ID_POSTPROCESS_PREDICTVALIDATIONRESPONSE 32806
#define ID_POSTPROCESS_COMPARE          32807
#define ID_POSTPROCESS_COMPARE32808     32808
#define ID_POSTPROCESS_PREDICT_TRAINING 32809
#define ID_POSTPROCESS_PREDICT_VALIDATION 32810
#define ID_POSTPROCESS_COMPARE_TRAINING 32811
#define ID_POSTPROCESS_COMPARE_VALIDATION 32812
#define ID_VIEW_SCROLLTOBOTTOM          32813
#define ID_FILE_EXPORT_DRM              32814
#define ID_POSTPROCESS_USEBALANCEDMODEL 32815
#define ID_BUILD_USEIPOPTFORANNTRAINING 32816
#define ID_BUILD_SCALELAGUERREANNINPUTS 32817
#define ID_BUILD_SCALEBALANCEDANNINPUTS 32818
#define ID_BUILD_USEIPOPTFORBALANCEDANNTRAINING 32819
#define ID_FILE_EXPORTLAGUERREWEIGHTMATRICES 32820
#define ID_BUILD_D                      32821
#define ID_D_DABNET                     32822
#define ID_D_NARMA                      32823
#define ID_CHOOSEHIGH_ACMSNAPSHOTFILE   32824
#define ID_FILE_EXPORTLO                32841
#define ID_FILE_EXPORTLOG               32842
#define ID_FILE_EXPORT_LOG              32843
#define ID_FILE_EXPORTTRAININGDATA      32844
#define ID_FILE_EXPORTVALIDATIONDATA    32845
#define ID_FILE_EXPORTACMFILE           32846
#define ID_FILE_EXPORT                  32847
#define ID_FILE_EXPORT32848             32848
#define ID_EXPORT_ACMFILE               32849
#define ID_EXPORT_ACMSNAP               32850
#define ID_EXPORT_SIMULINKFILE          32851
#define ID_EXPORT_TRAININGDATA          32852
#define ID_EXPORT_VALIDATIONDATA        32853
#define ID_EXPORT_D                     32854
#define ID_EXPORT_LOGFILE               32855
#define ID_FILE_EXPORT_ACMSNAP          32856
#define ID_FILE_EXPORTACMSNAPSHOTFILE   32857
#define ID_FILE_EXPORTSIMULINKFILE      32858
#define ID_POST_USEHIGH                 32859
#define ID_POSTPROCESS_USEHIGHFIDELITYHISTORY 32860
#define ID_UQ_SETNOISE                  32861
#define ID_UQ_CALCULATE                 32862
#define ID_EXPORT_COVARIANCEMATRICES    32863

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        137
#define _APS_NEXT_COMMAND_VALUE         32864
#define _APS_NEXT_CONTROL_VALUE         1054
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
